version: '3'

services:
  database:
    networks:
        - database
    container_name: YoutubeToMP3
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      # localhost port : container port
      - "1433:1433"
    restart: always
    volumes:
      - ./Data/mssql/data:/var/opt/mssql/data
      - ./Data/mssql/log:/var/opt/mssql/log
      - ./Data/mssql/secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=youtube123!
  
  login-backend-youtubetomp3:
    networks:
       - database
       - login-backend-youtubetomp3
    container_name: YoutubeMP3backend
    depends_on:
      - "database"
    ports:
      - "5001:5001"
      - "5000:5000"
    restart: always
    build: ./Login-Backend/YoutubeToMP3-Login-Backend/
    volumes:
      - ./YoutubeToMP3-Login-Backend:/usr/src/app
    expose:
      - 5001
      - 5000

networks:
  login-backend-youtubetomp3:
    driver: bridge
  database:
    driver: bridge
 
